# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StudyBuddy.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from QuestionDial import Ui_Dialog
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(10, 0, 131, 121))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("study buddy.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(180, -10, 521, 111))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.NumberQuestions = QtWidgets.QSpinBox(self.centralwidget)
        self.NumberQuestions.setGeometry(QtCore.QRect(340, 140, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.NumberQuestions.setFont(font)
        self.NumberQuestions.setObjectName("NumberQuestions")
        self.QuestionsLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuestionsLabel.setGeometry(QtCore.QRect(30, 130, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.QuestionsLabel.setFont(font)
        self.QuestionsLabel.setObjectName("QuestionsLabel")
        self.TimeAmount = QtWidgets.QSpinBox(self.centralwidget)
        self.TimeAmount.setGeometry(QtCore.QRect(430, 200, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.TimeAmount.setFont(font)
        self.TimeAmount.setObjectName("TimeAmount")
        self.TimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeLabel.setGeometry(QtCore.QRect(30, 190, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setObjectName("TimeLabel")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 250, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.urlLabel = QtWidgets.QLabel(self.centralwidget)
        self.urlLabel.setGeometry(QtCore.QRect(30, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.urlLabel.setFont(font)
        self.urlLabel.setObjectName("urlLabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 300, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.study)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Study Bully"))
        self.QuestionsLabel.setText(_translate("MainWindow", "Number of questions each round"))
        self.TimeLabel.setText(_translate("MainWindow", "Amount of time between each round in min."))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Please enter the URL here..."))
        self.urlLabel.setText(_translate("MainWindow", "Quizlet Link"))
        self.pushButton.setText(_translate("MainWindow", "STUDY"))

    def study(self):
        #time.sleep(5)
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        ui.inputChoice(Dialog, 2, "Lick My Balls")
        Dialog.show()
        Dialog.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
